//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermIT.Data.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist_List
    {
        public int value { get; set; }
        public string text { get; set; }
    }
}
