//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermIT.Data.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistTemplateItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ChecklistTemplateId { get; set; }
    
        public virtual ChecklistTemplate ChecklistTemplate { get; set; }
    }
}
